### ISSUE TITLE
Can't get icons to work

### ISSUE THREAD

**Issue by widdly-scuds** [nvtkaszpir/mumble-skin-gray#2]
The background is gray, but the icons are all still default (e.g, mouths don't change to arrows), even after restarting the client. I've tried placing all files but the .qss into a separate folder in skins/ and updating from version 1.2.9 to 1.3.0. Other users report it works fine with 1.3.0. I'm using Windows 7. Any ideas?

**Comment by nvtkaszpir** [comment]
After loading skin file restart application - it should fix the icons.
It's mentioned in Installation section.

**Comment by widdly-scuds** [comment]
Restarting doesn't fix the issue. That's why I'm stumped.

**Comment by nvtkaszpir** [comment]
I've got C:\Program files (x86)\Mumble\skins\gray\ and all files in there without subdirectories.
Mumble 1.3.0 loaded skin without an issue on Windows 7.

I suggest you ask mumble devs on IRC.

**Comment by nvtkaszpir** [comment]
won't fix.
